version: '3.1'
services:
  database:
    image: postgres:15
    ports:
      - '5454:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
  cache:
    image: redis:6
    ports:
      - '6379:6379'
